// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PoolerBotCS;

#nullable disable

namespace PoolerBotCS.Migrations
{
    [DbContext(typeof(PoolerDbContext))]
    [Migration("20260704081157_RemovedPlayerFields")]
    partial class RemovedPlayerFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PoolerBotCS.Models.BanchoLobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentMapId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BanchoLobbies");
                });

            modelBuilder.Entity("PoolerBotCS.Models.BanchoPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BanchoLobbyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BanchoLobbyId");

                    b.ToTable("BanchoPlayers");
                });

            modelBuilder.Entity("PoolerBotCS.Models.BanchoPlayer", b =>
                {
                    b.HasOne("PoolerBotCS.Models.BanchoLobby", null)
                        .WithMany("Players")
                        .HasForeignKey("BanchoLobbyId");
                });

            modelBuilder.Entity("PoolerBotCS.Models.BanchoLobby", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
